name: Deploy to staging
on:
  psuh:
    branches:
      -"main"

jobs:
  redeploy_everything:
    name: Deploying the everything to staging cluster

  steps:
    - name: SSH into server
    - run: |
        echo ${{ secrets.MY_SSH_PRIVATE_KEY}} &> ~/ssh_key
        ssh -i ~/ssh_key root@139.59.70.111
        cd monorepos-cloud-test/ && git pull
        pnpm install
        pnpm run build 
        pm2 restart http-server
        pm2 restart web
        pm2 restart web-server


