name: Deploy to staging
on:
  push:
    branches: [ main ]
     

jobs:
  redeploy_everything:
    runs_on: ubuntu-latest
    name: Deploying the everything to staging cluster
    steps: 
      - run: |
          echo ${{ secrets.MY_SSH_PRIVATE_KEY}} &> ~/ssh_key
          ssh -i ~/ssh_key root@139.59.70.111
          cd monorepos-cloud-test/ && git pull
          pnpm install
          pnpm run build 
          pm2 restart http-server
          pm2 restart web
          pm2 restart web-server


